import type { Tile } from './types';

export const TILES = [
  { id: '1m', suit: 'man', value: 1, symbol: '🀇', order: 0 },
  { id: '2m', suit: 'man', value: 2, symbol: '🀈', order: 1 },
  { id: '3m', suit: 'man', value: 3, symbol: '🀉', order: 2 },
  { id: '4m', suit: 'man', value: 4, symbol: '🀊', order: 3 },
  { id: '5m', suit: 'man', value: 5, symbol: '🀋', order: 4 },
  { id: '6m', suit: 'man', value: 6, symbol: '🀌', order: 5 },
  { id: '7m', suit: 'man', value: 7, symbol: '🀍', order: 6 },
  { id: '8m', suit: 'man', value: 8, symbol: '🀎', order: 7 },
  { id: '9m', suit: 'man', value: 9, symbol: '🀏', order: 8 },
  { id: '1p', suit: 'pin', value: 1, symbol: '🀙', order: 9 },
  { id: '2p', suit: 'pin', value: 2, symbol: '🀚', order: 10 },
  { id: '3p', suit: 'pin', value: 3, symbol: '🀛', order: 11 },
  { id: '4p', suit: 'pin', value: 4, symbol: '🀜', order: 12 },
  { id: '5p', suit: 'pin', value: 5, symbol: '🀝', order: 13 },
  { id: '6p', suit: 'pin', value: 6, symbol: '🀞', order: 14 },
  { id: '7p', suit: 'pin', value: 7, symbol: '🀟', order: 15 },
  { id: '8p', suit: 'pin', value: 8, symbol: '🀠', order: 16 },
  { id: '9p', suit: 'pin', value: 9, symbol: '🀡', order: 17 },
  { id: '1s', suit: 'sou', value: 1, symbol: '🀐', order: 18 },
  { id: '2s', suit: 'sou', value: 2, symbol: '🀑', order: 19 },
  { id: '3s', suit: 'sou', value: 3, symbol: '🀒', order: 20 },
  { id: '4s', suit: 'sou', value: 4, symbol: '🀓', order: 21 },
  { id: '5s', suit: 'sou', value: 5, symbol: '🀔', order: 22 },
  { id: '6s', suit: 'sou', value: 6, symbol: '🀕', order: 23 },
  { id: '7s', suit: 'sou', value: 7, symbol: '🀖', order: 24 },
  { id: '8s', suit: 'sou', value: 8, symbol: '🀗', order: 25 },
  { id: '9s', suit: 'sou', value: 9, symbol: '🀘', order: 26 },
  { id: 'east', suit: 'honor', value: 'east', symbol: '🀀', order: 27 },
  {
    id: 'south',
    suit: 'honor',
    value: 'south',
    symbol: '🀁',
    order: 28,
  },
  { id: 'west', suit: 'honor', value: 'west', symbol: '🀂', order: 29 },
  {
    id: 'north',
    suit: 'honor',
    value: 'north',
    symbol: '🀃',
    order: 30,
  },
  {
    id: 'white',
    suit: 'honor',
    value: 'white',
    symbol: '🀆',
    order: 31,
  },
  {
    id: 'green',
    suit: 'honor',
    value: 'green',
    symbol: '🀅',
    order: 32,
  },
  { id: 'red', suit: 'honor', value: 'red', symbol: '🀄', order: 33 },
] as const satisfies readonly Tile[];
